---
- hosts: all
  user: root
  become: yes
  tasks:
    - name: install git
      yum: 
        name: git
        state: present
    - name: install maven 
      yum: 
        name: maven
        state: present
    - name: tomcat download 
      unarchive: 
        src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.11/bin/apache-tomcat-10.1.11.tar.gz
        dest: /opt/ 
        remote_src: yes 
    - name: clone github repository
      git: 
        repo: https://github.com/SaiMaverick/gctech.git 
        dest: /opt/sai
        clone: yes  
    - name: maven build 
      command: mvn -f /opt/sai/pom.xml clean package 
    - name: tomcat deploy 
      shell: cp /opt/sai/target/*.war /opt/apache-tomcat-10.1.11/webapps/ROOT.war
    - name: tomcat run 
      shell: noup/opt/apache-tomcat-10.1.11/bin startup.sh
            
          
